language: python
dist: xenial
matrix:
  include:
  - python: '3.8'
    env: TOX_ENV=py38
  - python: '3.7'
    env: TOX_ENV=py37
  - python: '3.4'
    env: TOX_ENV=py34
  - python: '2.7'
    env: TOX_ENV=py27
install:
- pip install --upgrade pip
- pip install tox
script:
- tox -e $TOX_ENV
branches:
  only:
  - master
  - v0
deploy:
  provider: pypi
  user: criteo-marketing
  password:
    secure: AHQNztPvRBdd4G1uvQVEk4dUbJ2RG3M9Hg1cGqRLTURXzL/kpomoSsYzTwi/wlCV+lJAUqYl7yfSZQJ9rKZIZjPEX9qpbyn6epL7BYfJd7W6WyDPGrjwWbdtJdf/lNuQWrvz91X9ilPhRD4MMnPNEV2KBof1pKJqIPYTYx+ZV+b1wMtVFOXFrd8RxC8+DAkQXWxFdwKVRWkBTDDcsml4hEbWuwEPwX2uuYYjV8kAqDWPF9dCJOQsemkKb/C4epzeHslxYAJZ2tCYFlVHwMi4qpsm4XFr3FwxDiL+yC9ild0l8UeFuG/Zt35v3rd/xa+eQrQVRfU+jZ1/WBUtJSoKIJDNPdPTysqSHZ5JBvTHGgUOTh+n8aizrhdf7YtCm9aS9ztYQ5pL0VGNPW+sX6+30M5gqj/odr9R35CjGsoVDxuucM4H2GzBnigDEjdmmRQFJQUlN8KRfdFx2AOBaWGyXHFqFt/6wzU8AroDFtQQvO4ySBsEJ4vp/6+y3psuphux2lJXz15+Kgo/rNp1g7aSHdqZId9CrMhrBy4pr6QcLV7IHDbAxfdV+XY1E0janzg/W8AgnVtQ45qF1/itzbtrQmHF/TlrZ/qI/RX8uIuNMWRSNnI1eXGgb3HMdvyakkVVseI85nS6ZhGrrch/7DTO60P7ITQFbyN/02y4iGsNoII=
  skip-existing: true
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: E7C1irmC8PA5KDZHevHp+460vdaL3u6baxV3K2UNsVoOpwJHlIMKQkNOMjNghJTC4Vb7B1Wq95mO6GG/yuuF+0sVfuZH7UmvHc8ZTWI6lyOh2xHesDj8ywjpiC1YVww8vXo/QFNg17fQ7Qhposscs+1yyVURIgQIRrdyVNXPhHGfbGBlPKlFTHnNe1VlIQdjLvR613pVpe6B7FZHAz/sOeo7AuVwvmSjukwRYFDyuYKpJQutjVg/0iHRmBYoDC0zQ7BlEFnCbkbd+ZWRzniKkcfJ3iO1SGGZ6GbZR4tbHmM8jzy1g71tK5zrqeEuL9w4+cicXjEFw4h0cAzs2QZyAfRy0FjIw8G3PVKR9KE2huHap2Wlik+ZG8rGBYMwsHJUVkXXDPxwiW3QCxj1D25ozyh5cIunpKD5YTC5QYlHVpMkgzE6hdlbnVtzbuvouNd2QQfqIpAUn39AFrpTbD8pDcMIh1Vvb2CPff7GpCbp/FKkaBSpoLlLzNyF5tm6R1UYve8IHKrgXd+qbgPgjLyHrdnp+oB6ltUYuwwWUm3+c2Kn5PhpraWan/LLUw06d0Ns6NOjA6VA0QfK7FI2o0NNN/xOkvjCVoRfr5IYkfBJj/HA9dLSmDSqVZHqCRtlSvnSrpAYRFn8e4d+Rsx5cO8tg1rKRhyMXNIeLBF6h1gJffM=
