language: python
dist: xenial

matrix:
  include:
    - python: '3.7'
      env: TOX_ENV=py37
    - python: '3.4'
      env: TOX_ENV=py34
    - python: '2.7'
      env: TOX_ENV=py27

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox -e $TOX_ENV

branches:
  only:
    - master
    - v0

deploy:
  provider: pypi
  user: criteo-marketing
  password:
    secure: AHQNztPvRBdd4G1uvQVEk4dUbJ2RG3M9Hg1cGqRLTURXzL/kpomoSsYzTwi/wlCV+lJAUqYl7yfSZQJ9rKZIZjPEX9qpbyn6epL7BYfJd7W6WyDPGrjwWbdtJdf/lNuQWrvz91X9ilPhRD4MMnPNEV2KBof1pKJqIPYTYx+ZV+b1wMtVFOXFrd8RxC8+DAkQXWxFdwKVRWkBTDDcsml4hEbWuwEPwX2uuYYjV8kAqDWPF9dCJOQsemkKb/C4epzeHslxYAJZ2tCYFlVHwMi4qpsm4XFr3FwxDiL+yC9ild0l8UeFuG/Zt35v3rd/xa+eQrQVRfU+jZ1/WBUtJSoKIJDNPdPTysqSHZ5JBvTHGgUOTh+n8aizrhdf7YtCm9aS9ztYQ5pL0VGNPW+sX6+30M5gqj/odr9R35CjGsoVDxuucM4H2GzBnigDEjdmmRQFJQUlN8KRfdFx2AOBaWGyXHFqFt/6wzU8AroDFtQQvO4ySBsEJ4vp/6+y3psuphux2lJXz15+Kgo/rNp1g7aSHdqZId9CrMhrBy4pr6QcLV7IHDbAxfdV+XY1E0janzg/W8AgnVtQ45qF1/itzbtrQmHF/TlrZ/qI/RX8uIuNMWRSNnI1eXGgb3HMdvyakkVVseI85nS6ZhGrrch/7DTO60P7ITQFbyN/02y4iGsNoII=
  skip-existing: true
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack:
    secure: VE/9bo/W4w6UUId9uIWaNTZqn9yRHHnXvw5WMSRu6AKOoS94HCbCzZJX4taDRlY/DPab2mgkWP3aYn1wKX0c8W6bIZz4m26UTtbVccWrmx/9DGT+CJAMTZNgqgXPfuGC0TsSBJ0kawSZSnQYWN4AmhZNeEjhTv/XKuggwUGJT5Mu4aRrXG2HJhR7yUbTepojP6xSAqXn9WnSta3PEUU49LJhkTIYNBBhPdr1bRAo+nHYEo1IHFwX/6liNdFpJGkbEk3L/6i3ZXCrqkd19sVKQc0AUBp2U3ais9I8oJPQ4I4imLBrsxHXkWcZLYGfFXMI3+Ob9uAJ+lIp/CzIsGYafADQlJnQAk/9Esc2tZc6tpQN3MbeJpHXPda9c8LnY4GiJP3eL6vF86+Hainbs8mLWkg5wVxajKKyKXZ5FRm4LptXEfsILbO9IvqX1Mk6ye5yXlVcyYFcCWIKxIcif0BQDrdWH/i1cstZnE5Kc64i+qhRtwT9CgRGf3qrMxSzAS1VEn5WjIAzS/dAymGnU1bVpBy4cuAu+EAAE/OtupUv6QBE7yx3H1zHTnd8vb5QudcSizXRHBxv3Wmf9oFH9SOIz+hepo6zd4mQvwUXfQc0JEzQsX2ONfYgjI5DOkG9bGuak1DLFAdDxyO0CaVfNzw5O7JW43P2sma8jMdGeEU/lmw=
